### ISSUE TITLE
User coming form Boxy ;; anyway to have a dark themed google inbox?

### ISSUE THREAD

**Issue by arooni** [Thomas101/wmail-user-scripts#9]
I tried importing CSS from https://userstyles.org/styles/132513/google-inbox-dark-theme-september-2016 

without luck.  Would love a way to do this as I usually do my email at night and prefer a darker theme.

**Comment by Thomas101** [comment]
Hi, it looks like the style is wrapped in a non-standard `@-moz-document domain('inbox.google.com') {` class. If you remove that on the first line and also the very last close bracket `}` it should work

**Comment by arooni** [comment]
that fix worked great!  thanks for the tip!
